In [3]:
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')

# Tensor
Tensores é a generialização de vetores e matrizes(arrays multidimencionais) para dimensoes potencialmente maiores.
Os tensores possuem um "Data Type" uniforme e possuem um "Shape" que representa a dimensão do dado.

## Criando um Tensor

In [5]:
string = tf.Variable('Isto é uma string', tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

## Classificação de Tensores
Rank ou Degree é um termo que significa simplesmente o número de dimensões involvidas no tensor. Os tensores criados acima possuem um rank 0 e são chamados de escalares (scalar).

In [20]:
rank1_tensor = tf.Variable(['Teste', 'ok', 'yes'], tf.string)
rank2_tensor = tf.Variable([['teste', 'ok'], ['teste', 'positivo']], tf.string)

In [21]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [22]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [23]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape dos Tensores
O Shape do tensor é a quantidade de elementos que existem em cada dimensão. Pode acontecer do shape ser unknown(desconhecido).  
Shape é um atributo do objeto Tensor

In [26]:
string.shape

TensorShape([])

In [27]:
rank1_tensor.shape

TensorShape([3])

In [28]:
rank2_tensor.shape

TensorShape([2, 2])