In [29]:
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')

# Tensor
Tensores é a generialização de vetores e matrizes(arrays multidimencionais) para dimensoes potencialmente maiores.
Os tensores possuem um "Data Type" uniforme e possuem um "Shape" que representa a dimensão do dado.

## Criando um Tensor

In [30]:
string = tf.Variable('Isto é uma string', tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

## Classificação de Tensores
Rank ou Degree é um termo que significa simplesmente o número de dimensões involvidas no tensor. Os tensores criados acima possuem um rank 0 e são chamados de escalares (scalar).

In [31]:
rank1_tensor = tf.Variable(['Teste', 'ok', 'yes'], tf.string)
rank2_tensor = tf.Variable([['teste', 'ok'], ['teste', 'positivo']], tf.string)

In [32]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [33]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [34]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape dos Tensores
O Shape do tensor é a quantidade de elementos que existem em cada dimensão. Pode acontecer do shape ser unknown(desconhecido).  
Shape é um atributo do objeto Tensor

In [35]:
string.shape

TensorShape([])

In [36]:
rank1_tensor.shape

TensorShape([3])

In [37]:
rank2_tensor.shape

TensorShape([2, 2])

## Alterando o shape
A quantidade de elementos em um  tensor é o produto dos números do shape, As vezes existem shapes que possuem a mesma quantidade de elementos, o que torna conveniente a possibilidade de alterar o shape.

In [38]:
tensor1 = tf.ones([1,2,3]) # tf.ones criará um tensor com o shape [1,2,3] populado com 1
tensor2 = tf.reshape(tensor1, [2,3,1]) # alterar o shape para [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1]) #-1 fará com que o tamanho da dimensão seja calculado automáticamente

In [39]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Tipos de Tensores
Existem diferentes tipos de tensores, os mais utilizados são os seguintes:
* Variable
* Constant
* Placeholder
* Sparse Tensor
Com excessão das Variáveis, todos os demais tensores são imutáveis, ou seja, não é possível alterá-los durante a execução.

## Avaliando Tensores
Haverá a necessidade de vez em quando de avaliar um tensor, em outras palavras, obter o seu valor.  
No código abaixo a avaliação do tensor será registrada em um gráfico padrão, existe a possíbilidade de criar o próprio gráfico, mas o padrão será o suficiente por enquanto.
Existem diversas formas de fazer isso, mas nós faremos como descrito a seguir:  

In [40]:
print(tf.__version__)

2.9.1


In [42]:
with tf.compat.v1.Session() as sess:
    print(tensor1.eval)

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>>
